Fix and Plugin
th-ch/youtube-music pull request #1159
Opened 2023-05-24 14:38 UTC by Sickjuicy

Fixes the Windows ScaleFactor and add a plugin to autopause at starup of the up but has autoplay still enabled.

2023-06-05 19:26 UTC, Sickjuicy reviewed
Adds the scalefactor, for one monitor or multiple, testet on 2 monitors and one, on my laptop and pc  also sandbox.

Laptop zoom: 150% and than 100%
PC two monitor: 
1. zoom: 100%
2. zoom: 150%

2023-09-17 17:05 UTC, JellyBrick requested changes

2023-09-17 17:05 UTC, JellyBrick commented on plugins/startup-FN/back.js
Why did you add this plugin?

2023-09-17 17:05 UTC, JellyBrick commented on plugins/startup-FN/front.js
Same as the comment above.

2023-09-17 17:14 UTC, Sickjuicy commented on plugins/startup-FN/back.js
I have not seen the function in the shortcuts plugin, the other plugin is there for when I start the PC that you can use the function keys directly without the need to move the program into focus. I have noticed in general in the installer version the function keys often do not work but in the standalone version. I have the plugins in the after no also deleted again, unfortunately, this is very confusing in github just, should I reopen the post? 
PS: english is not my main language

2023-09-17 22:48 UTC, Sickjuicy commented on plugins/startup-FN/back.js
I deleted the plugin.

2023-09-17 23:08 UTC, JellyBrick requested changes

2023-09-17 23:08 UTC, JellyBrick commented on index.js
> +	}
```suggestion
	if (size && size.width && size.height) {
		const scaledSize = {
			width: size.width / scaleFactor,
			height: size.height / scaleFactor,
		};
		win.setSize(scaledSize.width, scaledSize.height);
	}
```

2023-09-17 23:08 UTC, JellyBrick commented on index.js
> +	}
```suggestion
	if (position && position.x && position.y) {
		const scaledPosition = {
			x: position.x / scaleFactor,
			y: position.y / scaleFactor,
		};
		win.setPosition(scaledPosition.x, scaledPosition.y);
	}
```

2023-09-18 00:04 UTC, JellyBrick approved these changes

2023-10-06 19:07 UTC, th-ch commented
Thanks, ported in https://github.com/th-ch/youtube-music/commit/d36fb592d0ad12152e2d46429bbb8bb13519e63e in TS!

2023-10-06 19:07 UTC, closed without merging