Album actions
th-ch/youtube-music pull request #1515
Opened 2023-12-10 09:36 UTC by MiepHD

Adds Undislike, Dislike, Like and Unlike buttons to apply this to all songs in a playlist or album.
![image](https://github.com/th-ch/youtube-music/assets/63968466/b2a249c1-7b2c-42bd-b011-a21115ac736e)
Fixes #831

2023-12-10 14:00 UTC, ArjixWasTaken commented
Don't add `enabled: true` in the config....
Your plugin must not be enabled unless specified otherwise by the user's config.

2023-12-10 14:04 UTC, MiepHD commented
I enabled it by default because it just adds these buttons to the UI. If you don't click the buttons nothing happens. But I can remove that if that's a problem

2023-12-10 14:07 UTC, ArjixWasTaken commented
Since it does not fix a bug, I consider it an additional feature.
I guess I'll leave it up to @JellyBrick

2023-12-10 19:35 UTC, JellyBrick commented
![image](https://github.com/th-ch/youtube-music/assets/16558115/6adf3342-85b3-44fc-8f08-f598480b92f4)

The shapes of the buttons can be confusing to users.

2023-12-10 19:51 UTC, MiepHD commented
Why? Should I add an explanation what they do?

2023-12-10 21:02 UTC, JellyBrick commented
What about showing just one of each button? (1 dislike button, 1 like button)
- If any item is "Liked", show a filled "Like" button; if any item is "Disliked", show a filled "Dislike" button
- If both "Liked" and "Disliked" are checked, show both filled buttons

2023-12-11 16:59 UTC, MiepHD commented
Now it shows a 
- undislike button if any item is disliked
- dislike button if any item isn't disliked
- like button if any item isn't liked
- unlike button if any item is liked

2023-12-12 01:04 UTC, JellyBrick requested changes

2023-12-12 01:04 UTC, JellyBrick commented on src/plugins/album-actions/index.ts
> +    changeobserver: null as MutationObserver | null,
use camelCase

2023-12-12 01:04 UTC, JellyBrick commented on src/plugins/album-actions/index.ts
> +          : document.querySelector('ytmusic-playlist-shelf-renderer');
```suggestion
        const playlist = document.querySelector('ytmusic-shelf-renderer') ?? document.querySelector('ytmusic-playlist-shelf-renderer');
```

2023-12-12 01:04 UTC, JellyBrick commented on src/plugins/album-actions/index.ts
> +        : document.querySelector('ytmusic-playlist-shelf-renderer');
ditto

2023-12-12 01:04 UTC, JellyBrick commented on src/plugins/album-actions/index.ts
> +      }
```suggestion
      playlistButtons?.forEach((elem) => elem.click());
```

2023-12-12 01:04 UTC, JellyBrick commented on src/plugins/album-actions/index.ts
> +            console.log(count);
```suggestion
```

2023-12-12 01:04 UTC, JellyBrick commented on src/plugins/album-actions/index.ts
> +        }
How about `.filter()` instead of this logic?

2023-12-12 02:37 UTC, inson1 commented
> Now it shows a
> 
> * undislike button if any item is disliked
> * dislike button if any item isn't disliked
> * like button if any item isn't liked
> * unlike button if any item is liked

Just another opinion. I hope you dont mind it :) That is standard, yes. But it isnt perfect :/. 

What about highlighted (bold lines?) like/dislike button if some are liked/disliked, but not all? (I think that is also used somewhere) Or something like that? Maybe like/dislike button with full white, but black "ball" inside
Just something so normal user would get it and "profi" user would know if all songs are liked or disliked.
Or another mode for this?

2023-12-27 17:24 UTC, Su-Yong reviewed
It seems memory leak bug

2023-12-27 17:24 UTC, Su-Yong commented on src/plugins/album-actions/index.ts
> +      });
```suggestion
    waitForElem(selector: string) {
      let limit = 0;
      return new Promise((resolve, reject) => {
        const interval = setInterval(() => {
          limit += 1;
          if (limit > 3000) {
            clearInterval(interval);
            reject();
          }
          const elem = document.querySelector(selector);
          if (!elem) return;

          clearInterval(interval);
          resolve(elem);
        });
      });
```

2023-12-27 17:24 UTC, Su-Yong commented on src/plugins/album-actions/index.ts
> +      });
```suggestion
      }).catch(() => {
        // Cannot find element
      });
```

2023-12-27 19:24 UTC, Su-Yong approved these changes

2023-12-29 15:13 UTC, JellyBrick approved these changes

2023-12-29 15:13 UTC, merged