refactor(in-app-menu): refactor `in-app-menu` plugin
th-ch/youtube-music pull request #1710
Opened 2024-02-03 21:09 UTC by Su-Yong

# Summary
- refactor `in-app-menu` plugin

# Notes
- apply `solid-js`
- resolve #1709
- resolve #1705

2024-02-04 14:58 UTC, JellyBrick requested changes

2024-02-04 14:58 UTC, JellyBrick commented on package.json
> +    "vite-plugin-solid": "^2.9.1",
pin deps version
```suggestion
    "vite-plugin-solid": 2.9.1",
```

2024-02-04 14:59 UTC, JellyBrick approved these changes

2024-02-04 15:01 UTC, JellyBrick requested changes

2024-02-04 15:01 UTC, JellyBrick commented on package.json
> +    "vite-plugin-solid": 2.9.1",
```suggestion
    "vite-plugin-solid": "2.9.1",
```

2024-02-04 15:57 UTC, JellyBrick approved these changes

2024-02-05 13:26 UTC, merged

2024-02-18 16:38 UTC, IncognitoFawkes commented
Issue not fixed for me in the new 3.3.1.0 for the in-app menu. I haven't observed the repeating menu bar yet, so maybe that's fixed, but the buttons on the top-right corner are still inaccessible. I can't click on Music Together or my profile when the app is open.