feat(downloader): New option to download on finish
th-ch/youtube-music pull request #1964
Opened 2024-04-11 16:46 UTC by Johannes7k75

This adds an option to the downloader menu. 
When the option is activated it tracks the time that is elapsed and then if the rest time of the song is below 20 seconds it downloads the song.

The range is 20 seconds for when you skip the last bit of the song.

2024-04-13 07:40 UTC, JellyBrick requested changes

2024-04-13 07:40 UTC, JellyBrick commented on src/plugins/downloader/main/index.ts
> -  increasePlaylistProgress: (value: number) => void = () => {},
What is this change?

2024-04-13 07:40 UTC, JellyBrick commented on src/plugins/downloader/main/index.ts
> +    const config = await getConfig();
Checking `config` in a callback is not a good idea (IO overhead)
How about calling `registerCallback` if `downloadOnFinish` is true?

2024-04-14 13:35 UTC, ArjixWasTaken commented
What happens on songs with a length of 40 seconds?

20 seconds would be the half, and not the "last bit"

Either make it configurable based on how big a song is, or make it a percentage (like 99%)

2024-04-14 20:11 UTC, Johannes7k75 commented
> What happens on songs with a length of 40 seconds?
> 
> 20 seconds would be the half, and not the "last bit"
> 
> Either make it configurable based on how big a song is, or make it a percentage (like 99%)

If made it so that you can configure "last x seconds" and "after x percent".
The you have the choice between these to options
![image](https://github.com/th-ch/youtube-music/assets/57235955/c05a1246-0298-4bcc-82b6-7f513b5ab29f)

And here the window where you can configure the two options (if clicked on "Advanced")
![image](https://github.com/th-ch/youtube-music/assets/57235955/a04583fb-7408-4ca7-b91d-d566400cbba0)

2024-04-30 13:34 UTC, ArjixWasTaken commented
I will test and review this later today.

2024-04-30 20:35 UTC, ArjixWasTaken commented on .github/workflows/build.yml
> +  workflow_dispatch:
why?

2024-04-30 20:36 UTC, ArjixWasTaken commented
Why does your PR touch things unrelated to the download plugin?

2024-04-30 20:48 UTC, ArjixWasTaken commented
Ok, it seems to work fine on my machine.

The only issue that I noticed is kinda unrelated to this plugin, but the song change callbacks are not called for the auto-play song on start-up. (which is totally not the responsibility of this plugin to fix)

2024-04-30 23:47 UTC, Johannes7k75 commented
> Also, maybe it would be a good idea to allow a separate folder for the auto-downloaded tracks.

I try to add it in the next days

2024-05-24 23:40 UTC, JellyBrick requested changes

2024-05-24 23:40 UTC, JellyBrick commented on plugins/scroll-down/front.js
What is this?

2024-07-10 09:29 UTC, JellyBrick commented
I'm busy with my job, so I can't review it right now.
I'll check this out in a couple days.

Thanks for your contribution!

2024-07-14 12:51 UTC, JellyBrick approved these changes

2024-07-14 13:00 UTC, merged

2024-07-15 02:07 UTC, MulverineX commented
Does this actually use the cached audio Blob? Or does it effectively download the song twice?

2024-07-15 02:08 UTC, MulverineX commented
@Johannes7k75

2024-07-15 02:11 UTC, Johannes7k75 commented
It just calls the downloadSong function

2024-07-15 02:11 UTC, Johannes7k75 commented
So i think it downloads the song twice

2024-07-15 02:40 UTC, MulverineX commented
would be really awesome if this somehow didn't use that

2024-07-16 14:07 UTC, Johannes7k75 commented
Would it really benefit from using the cached audio blob?
And beyond that, I don't know enough about it.