add prettier rules to eslint
th-ch/youtube-music pull request #2438
Opened 2024-09-21 23:48 UTC by ArjixWasTaken

2024-09-21 23:49 UTC, ArjixWasTaken commented
how are there already conflicts?

2024-09-21 23:49 UTC, ArjixWasTaken commented
fucking renovate bot...

2024-09-21 23:50 UTC, ArjixWasTaken commented
I ain't resolving those conflicts, renovate is annoying for PRs.........

2024-09-21 23:56 UTC, ArjixWasTaken commented
does it make sense to merge renovate PRs so frequently?
it's not as if they are included in a release as frequently, so they don't benefit the users

2024-09-28 06:32 UTC, JellyBrick requested changes

2024-09-28 06:32 UTC, JellyBrick commented on package.json
> +    "eslint-config-prettier": "^9.1.0",
```suggestion
    "eslint-config-prettier": "9.1.0",
```

version pinning

2024-10-13 09:24 UTC, closed without merging