fix: discord rich presence connection status
th-ch/youtube-music pull request #2714
Opened 2024-12-14 02:47 UTC by daika7ana

Fixed the false "Connected" status in the `discord-rich-presence` plugin. 

The `isConnected()` function now includes an extra check to ensure the Discord RPC is actually connected, not just instantiated.
This makes the connection status properly reflect the RPC client's state. 

Fixes issue #2620.

2024-12-14 12:00 UTC, JellyBrick requested changes

2024-12-14 12:00 UTC, JellyBrick commented on src/plugins/discord/main.ts
> +  info.rpc !== null && info.rpc?.isConnected === true;
```suggestion
  info.rpc?.isConnected;
```

2024-12-14 18:58 UTC, daika7ana commented on src/plugins/discord/main.ts
> +  info.rpc !== null && info.rpc?.isConnected === true;
Fixed in a separate commit to keep it clean as a one-liner. Guess I was a bit tired when I made the fix and missed the obvious.

2024-12-15 12:59 UTC, JellyBrick approved these changes

2024-12-15 13:00 UTC, merged