feat(synced-lyrics): init romanization!
th-ch/youtube-music pull request #2790
Opened 2024-12-28 00:43 UTC by ArjixWasTaken

Started working on romaji support!

TODO:
 - Japanese [x]
- Mandarin [ ]
- Korean [ ]

Preview:
![image](https://github.com/user-attachments/assets/8c68284f-e016-41d5-a842-c224bdcfb8e8)

---

Blocked by #2788

2024-12-29 01:17 UTC, ArjixWasTaken commented
I think there is a problem with the pinyin library...

![image](https://github.com/user-attachments/assets/ffeff5e3-369e-4347-893a-708a43b87d14)

I've studied chinese for 2 years, and that should have been `ni de`, I don't even know what `teki` is, but don't take my chinese to be trustworthy :pensive:

you can listen to that song yourself, to see that they say "ni de" and not "ni teki"
https://music.youtube.com/watch?v=16M3bHVbtqY&t=58

2024-12-29 01:27 UTC, ArjixWasTaken commented
This brings an issue to the surface, should I run only one romanizer and not all of them?
Like, Japanese have many chinese characters, that are often pronounced in different ways, like the example above, where `de` became `teki`

If I run the pinyin romanization first, it will affect japanese lyrics, but if I run the japanese romanization first, it will affect chinese lyrics.....

2024-12-29 01:51 UTC, ArjixWasTaken commented
Ok, for now I ended up with the following solution to the problem described earlier:

- if a line contains hiragana or katakana, it is japanese, if it only contains kanji and doesn't use hiragana/katakana at all, it is chinese

That fixed the issues I encountered in chinese and japanese lyrics, unfortunately, if the lyrics are entirely in kanji, I can't do much about it 😔 

More creative solutions are always welcome!

2024-12-29 09:47 UTC, JellyBrick commented
> Ok, for now I ended up with the following solution to the problem described earlier:
> 
> * if a line contains hiragana or katakana, it is japanese, if it only contains kanji and doesn't use hiragana/katakana at all, it is chinese
> 
> That fixed the issues I encountered in chinese and japanese lyrics, unfortunately, if the lyrics are entirely in kanji, I can't do much about it 😔
> 
> More creative solutions are always welcome!

You can use lingua for language detection

https://github.com/pemistahl/lingua-js

2024-12-29 11:19 UTC, ArjixWasTaken commented
That sounds a little bit overkill, and honestly, I doubt it would work unless it knows the difference between Chinese and Japanese grammar, because a lot of kanji characters are 1:1 the same as Chinese characters

2024-12-29 16:21 UTC, JellyBrick commented
If a sentence contains shinjitsu, it can be considered Japanese (although there are cases where it uses kanji, but in those cases I think it's mostly distinguishable by the presence of hiragana and katakana)

- https://github.com/pemistahl/lingua-rs/pull/381
- https://github.com/pemistahl/lingua-go/issues/38

2024-12-29 16:27 UTC, JellyBrick commented
If a sentence contains shinjitai (新字体), it can be considered Japanese (although there are cases where it uses kanji (旧字体), but in those cases I think it's mostly distinguishable by the presence of hiragana and katakana)

- https://github.com/pemistahl/lingua-rs/pull/381
- https://github.com/pemistahl/lingua-go/issues/38

2024-12-29 16:33 UTC, JellyBrick commented
Also, if a sentence contains Korean kanji, it can be considered Korean.
- https://namu.wiki/w/%EA%B5%AD%EC%9E%90(%ED%95%9C%EC%9E%90)
  - (Korean)

2024-12-29 18:15 UTC, ArjixWasTaken commented
Hmm, I think it should be safe to assume that if at least one line contains katakana/hiragana, then we are dealing with japanese for all lines.

If no japanese/korean is detected anywhere, that's when I should use the pinyin library, I think that should work fine for most cases?

I really don't want to add more dependencies

2024-12-29 19:40 UTC, ArjixWasTaken commented
It should be much more reliable now, I doubt there are many japanese songs that are exclusively in kanji, if at least one line contains one character that is hiragana/katagana, then all lines are treated as japanese

2024-12-29 20:25 UTC, ArjixWasTaken commented
es-hangul doesn't have a method to test if a given text contains hangul, so I found some regex to do the job
the regex doesn't have to be perfect, don't overthink it, we just want to know if at least one line contains a hangul character or not, to determine what romanizer to use, I know korean unicode is complex, but this really should be enough

---

![image](https://github.com/user-attachments/assets/19945016-6462-4a19-ac7b-5b09ff132876)

2024-12-29 21:18 UTC, kimjammer commented
Got an edge case for you, some songs are in 3 languages. Currently it looks like only one romanizer can be active for a song. In this particular song, Japanese and Korean don't appear on lines together so you could just pick the romanizer line by line, but I'm not sure if there are songs out there that do.
![image](https://github.com/user-attachments/assets/060d2886-2cee-4001-9030-aeb8305979c1)
We love CJK 😃😃😃.
Anyhow, looking forward to this feature.
(I'm also going to assume you've noticed that the fancy font size isn't being applied correctly)

2024-12-29 21:20 UTC, ArjixWasTaken commented
> Got an edge case for you, some songs are in 3 languages. Currently it looks like only one romanizer can be active for a song. In this particular song, Japanese and Korean don't appear on lines together so you could just pick the romanizer line by line, but I'm not sure if there are songs out there that do. ![image](https://private-user-images.githubusercontent.com/41841812/399187378-060d2886-2cee-4001-9030-aeb8305979c1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU1MDc0NTUsIm5iZiI6MTczNTUwNzE1NSwicGF0aCI6Ii80MTg0MTgxMi8zOTkxODczNzgtMDYwZDI4ODYtMmNlZS00MDAxLTkwMzAtYWViODMwNTk3OWMxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI5VDIxMTkxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE2NmUzMGI0MjdhMGVlYWFkY2E2MDVmNjc3NmU3MzIwODU3M2Y0ZDJmMTgzYmY5ZDIxZjJjNmE1OTU1OGZkNzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.bkPbyOm1QgjMKde9eE7FnfSQkn9VltBfiG0o4anZX9Y) We love CJK 😃😃😃. Anyhow, looking forward to this feature. (I'm also going to assume you've noticed that the fancy font size isn't being applied correctly)

fuck those songs (╯°□°）╯︵ ┻━┻

2024-12-29 21:27 UTC, ArjixWasTaken commented
@kimjammer could you send a list of 2-3 songs that have lyrics and contain chinese+korean+japanese?

2024-12-29 22:30 UTC, kimjammer commented
By 3 languages I meant Japanese + English + Korean, but I think it would be good to have a list of mixed language songs for testing so:
JE, KE = Japanese and English on same line, Korean and English on same line, Japanese and Korean NOT in same line

J, K, JE, KE: LIT - STAYC
J, K, JE, KE, JK, JKE: Bad Girl for You - EXID
K, C, KE: HIGHLIGHT - SEVENTEEN
C, CK, CE: HWAA (Chinese Ver.) - (G)I-DLE
C, J, K, CE, KE: From Home - NCT U

I don't think any song has Chinese and Japanese on the same line
Good luck!

2025-01-01 22:50 UTC, ArjixWasTaken commented
@kimjammer can you confirm if this is correct?

https://music.youtube.com/watch?v=WRWg4EA_dwQ&t=161
![image](https://github.com/user-attachments/assets/7bbe2c99-dee2-4ed6-84e3-dd3a788127ae)

2025-01-01 23:58 UTC, kimjammer commented
I pulled the pr to test it and I can confirm that the top 4 songs look right to me.

2025-01-05 00:23 UTC, ArjixWasTaken commented
I've implemented everything I planned to, so I am now ready to accept code reviews!

2025-01-05 00:36 UTC, ArjixWasTaken commented
> (I'm also going to assume you've noticed that the fancy font size isn't being applied correctly)

@kimjammer can you elaborate on that? does that still happen with the latest commit?

2025-01-07 00:54 UTC, kimjammer commented on src/plugins/synced-lyrics/style.css
> +  --lyrics-font-size: clamp(1.4rem, 1.1vmax, 3rem) !important;
The "!important" on this line seems to prevent this variable from being set correctly in the code. In the last commit, the fancy mode follows the `clamp(1.4rem, 1.1vmax, 3rem)` font-size even though it should be `3rem`. Removing !important seems to fix the problem.

2025-01-07 00:58 UTC, kimjammer commented
One more thing, are you planning to have a menu toggle for romanization?

2025-01-07 01:09 UTC, kimjammer commented on src/plugins/synced-lyrics/style.css
> +  --lyrics-font-size: clamp(1.4rem, 1.1vmax, 3rem) !important;
This also makes the romanization the full 3rem, it might be worth considering making the romanization smaller than 3rem so the lyrics page isn't too cramped.

2025-01-23 05:02 UTC, ValiantZippu commented
Nice work but I hope the design would be kind of flawless and modern like the extention Better Lyrics - Chrome
And also translation of lyrics . and can the ui kind of be like this ? the grayish bar and the black side bar looks not as clean as this one . 

![image](https://github.com/user-attachments/assets/c665780e-9bad-4669-9a1a-37d07aaa1fa2)

2025-01-23 07:05 UTC, ArjixWasTaken commented
ngl I find that ugly

2025-01-23 12:34 UTC, ValiantZippu commented
> ngl I find that ugly

I respect your taste but I think everyone has their own choice it would be cool to have a toggle in the ambient plugin to make the entire now playing page like that . Main highlight is the lyrical aesthetic from it

2025-01-23 12:38 UTC, ArjixWasTaken commented
@ValiantZippu 

I don't want or need you to respect my taste, and that should apply in reverse as well,
instead of suiting everyone's taste (impossible to do), focusing on a simple interface and letting the community enhance it would be the best

https://github.com/th-ch/youtube-music/issues/2540

if you'd like, you can make suggestions on that issue, to make it a reality

2025-02-08 15:53 UTC, ArjixWasTaken commented
Done with uni exams!

2025-02-21 22:52 UTC, ArjixWasTaken commented
too lazy to get back at this, someone give me motivation (insults)

2025-02-21 23:13 UTC, kimjammer commented
plz finish I've been waiting patiently for two months 🙏

2025-02-22 13:18 UTC, ArjixWasTaken commented
oh darn it, fine

2025-03-01 19:37 UTC, DeltaLaboratory commented
When we add some lyric translate feature, what would romanized+translated lyric UI look like?
Just asking because I am willing to add translate feature based on this draft.

2025-03-02 01:52 UTC, ArjixWasTaken commented
I am going to work on this tomorrow (on the 2nd of the month), and will make it ready for merge.

---

@DeltaLaboratory I guess it'd be below the romanized line? we'd need to add settings so it's the UI is not cluttered tho

2025-03-03 00:08 UTC, ArjixWasTaken commented
tweaked the CSS a bit,
![image](https://github.com/user-attachments/assets/0e21a032-e9f0-432c-be86-25e6523218e0)

2025-03-03 00:13 UTC, ArjixWasTaken commented
I am ready for reviews, fire them at me!

2025-03-03 01:53 UTC, kimjammer approved these changes
LGTM! I tested it, and it works perfectly for all songs that don't contain both J and C. Thank you for finishing it!

2025-03-26 06:36 UTC, JellyBrick requested changes

2025-03-26 06:36 UTC, JellyBrick commented on src/plugins/synced-lyrics/backend.ts
> +        pinyin(text, {
Korean hanja are pronounced differently from Chinese.

2025-03-26 10:51 UTC, JellyBrick approved these changes

2025-03-26 10:52 UTC, ArjixWasTaken commented
@JellyBrick thanks for improving hangul!

I noticed that there is a regression to the `canonicalize` function, as it no longer fixes `" datte "` to `"datte"` as seen in

before:
![image](https://github.com/user-attachments/assets/b16de5d0-23b9-474c-91f7-54ffeb00284f)

after:
![image](https://github.com/user-attachments/assets/2f6bc5ad-7d03-45c3-b5cd-ae1673b7652f)

---

other than that, amazing work!

2025-03-26 11:04 UTC, ArjixWasTaken commented
Since we are on the topic of improving the accuracy of the romanization, what can we do about japanese?

`獣は砂を一握り撒いた` gets romanized as `shishi wa suna o ichi nigiri mai ta`, but what I can hear is `kemono wa su na wo`

I don't know japanese, but I trust my ears to recognize such a different :p

2025-03-26 11:18 UTC, ArjixWasTaken commented
> > Since we are on the topic of improving the accuracy of the romanization, what can we do about japanese?
> > `獣は砂を一握り撒いた` gets romanized as `shishi wa suna o ichi nigiri mai ta`, but what I can hear is `kemono wa su na wo, hitonigiri maita`
> > I don't know japanese, but I trust my ears to recognize such a difference :p
> > EDIT: google translate says "Kemono wa suna o hitonigiri maita", which sounds accurate
> 
> @ArjixWasTaken The reason this issue occurs is that Kanji in CJK languages can be read differently depending on context and situation. For example, in the sentence above, the character "獣" meaning "beast" can be read as "けだもの" (kedamono), "けもの" (kemono), or "しし" (shishi). Another example is "行こう" which means "let's go" In a literary or old-fashioned context, it may be read as "yukou" while in everyday usage, it is typically read as "ikou" There is no way to solve this issue other than using AI.

ig in that case, I'll have to think of gathering user-submitted corrections in a database like lrclib

2025-03-26 11:21 UTC, ArjixWasTaken commented
actually, should I add support for google's API?
https://cloud.google.com/translate/docs/advanced/romanize-text

the user would have to provide the API keys

2025-03-26 11:25 UTC, JellyBrick commented
I will merge this PR for now and work on improvements later.

2025-03-26 11:29 UTC, merged

2025-05-04 10:16 UTC, AMZMA commented
> actually, should I add support for google's API? https://cloud.google.com/translate/docs/advanced/romanize-text
> 
> the user would have to provide the API keys but it doesn't have a free tier as far as I can see
> 
> the pricing calculator says that translating 500.300 characters is free, anything above that costs money, dunno how that works

yes, please. and add support for any other non Roman text (Russian, Greek, Arabic, Hindi, etc).

this one here says its free and unlimited
https://github.com/ssut/py-googletrans

google transliteration is superior than any other.