Add "Picture in picture" plugin
th-ch/youtube-music pull request #674
Opened 2022-04-07 19:48 UTC by th-ch

This PR implements a raw version of PiP for https://github.com/th-ch/youtube-music/issues/656 - first version re-uses the main window as having a new one requires way more work.

2022-04-08 11:27 UTC, Araxeus commented
Doesn't really look like PiP to me, it looks like the native fullscreen mode (`f`) except its windowed

also it seems like pressing the "PiP" button cause the fullscreen mode to be windowed (but with the fullscreen ui)

so maybe this should just be an option (like "Windowed Fullscreen Mode") in the main menu? (Its more of a global toggle so I don't think it should be in the song menu)

There's Also an error/bug: ⚠️ 
trying to log in after having used "PiP" causes the app to freeze, console says
`TypeError: Cannot read properties of undefined (reading 'hide')
    at togglePiP (C:\Git\youtube-music\plugins\picture-in-picture\back.js:29:12)`

2022-04-08 11:43 UTC, Araxeus requested changes

2022-04-08 11:43 UTC, Araxeus commented on plugins/picture-in-picture/back.js
> +		app.dock.hide();
```suggestion
		app.dock?.hide();
```

2022-04-08 11:43 UTC, Araxeus commented on plugins/picture-in-picture/back.js
> +		app.dock.show();
```suggestion
		app.dock?.show();
```

2022-04-08 11:43 UTC, Araxeus commented on plugins/picture-in-picture/back.js
> +	win.setWindowButtonVisibility(!isInPiPMode);
```suggestion
	win.setWindowButtonVisibility?.(!isInPiPMode);
```

2022-04-08 11:47 UTC, Araxeus commented
Ok sorry i'm just immediately writing as I'm thinking of stuff but ignore what I said about the size and name and all that

It just needs to behave correctly when entering fullscreen mode because right now thats buggy

also there should be a plugin option to set a hotkey for PiP

Good work 😄

2022-04-09 12:43 UTC, Araxeus commented
2 more changes related to other plugins that should maybe come in follow up PR?
* precise-volume hud position needs to be tweaked if both pip AND in-app-menu are active
  (the volume hud is positioned inside the in-app-titlebar somehow)
* since in-app-menu is contained within the window, it shows only the topmost options in this mode, thus the most important menu options should maybe be moved up (View-exit/restart) (Options-AlwaysOnTop)

2022-04-09 19:11 UTC, Araxeus commented
- [ ] right now its pretty annoying to exit the pip mode. there are 2 good solutions that I think could be both implemented:
  1. in `togglePiP` when PiP is activated ,register click event for t
   `$('.exit-fullscreen-button').addEvent -> onClick = togglePiP()` / `togglePictureInPicture()`
  and when its deactivated restore it
  2. like I wrote above, a custom keybind to toggle PiP

- [ ] on PiP start: if browserWindow is maximized, unmaximize it to avoid weird interaction

- [ ] some more css changes for more visibility in the playerbar:
  ```css
  ytmusic-player-bar.pip svg,
  ytmusic-player-bar.pip .time-info,
  ytmusic-player-bar.pip yt-formatted-string,
  ytmusic-player-bar.pip .yt-formatted-string {
	  filter: drop-shadow(2px 4px 6px black);
	  color: white !important;
	  fill: white !important;
  }
  ```
   - fix playerbar's artist/album string which instead of being `yt-formatted-string`  element they are links that have that as class.
   - fix `.timeInfo` which is a span that shows the current time (only when window is bigger than default PiP but still)
   - fix add `!important` to color to fix it not applying to artist name
   - fix `fill: white !important` mainly to fix `#button.dropdown-trigger` that didn't get filled by using `color

2022-04-09 19:53 UTC, th-ch commented
Interesting feedback, thanks for the involvement! The PR is getting big and it gives a first version of the plugin (not perfect but good enough for a first iteration) so I'll merge it as is, and we can follow up with the remaining improvements (which make sense)! 🚀

2022-04-09 19:53 UTC, merged

2022-04-09 20:06 UTC, Araxeus commented
>  I don't think that alwaysontop should be enabled by default since you can just enable it in the options
(maybe a plugin option to automatically enable alwaysontop but it shouldn't force this behavior)

^ do you agree with that?

should I open PR's about stuff I wrote since you closed this?

2022-04-09 20:08 UTC, th-ch commented
definitely, making it a user choice is better than forcing it!

2022-04-09 20:13 UTC, Araxeus commented
also im thinking maybe its better if the PiP button is inserted on the video overlay (like the "quality changer" button )
![image](https://user-images.githubusercontent.com/78568641/162590071-c0197ac5-5804-442b-99db-0a231e9da7c0.png)
which would be way easier to access

(and then to exit that you could press the exit-fullscreen button i mentioned above / use the custom keybind)